config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get "about" => "pages#about"
  get "songs" => "pages#songs"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
	has_attached_file :image, styles: { medium: "300 x 300", thumb: "100 x 100"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	validates :description, presence: true
	validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def signup
  end

  def songs
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all.order(updated_at: :desc)
  end

  def show
  end

  def new
      @pin = current_user.pins.build
  end

  def edit
  end

  def create
      @pin = current_user.pins.build(pin_params)
      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.'
      else 
        render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: 'Not authorised.' if @pin.nil?
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        PhotoRack
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class = "collapse navbar-collapse" id = "bs-example-navbar-collapse-1">
      <ul class = "nav navbar-nav navbar-right ">
           <li><%= link_to "Home", root_path %></li>
           <li><%= link_to "About", about_path %></li>
           <% if user_signed_in? %>

            <li><%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span>New Pin
            <% end %>
            </li> 
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
           <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
           <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo Rack</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/_home.html.erb
<!-- class = "jumbotron center" allows the jumbotron to be in the centre-->

<div class = "jumbotron center">
	<p>
		<% if user_signed_in? %>
			<h2>Welcome Back</h2> 
			<%= link_to new_pin_path, class: "btn btn-primary btn-lg" do%>
				<span class="glyphicon glyphicon-plus"></span>New Pin
				</button>
			<% end %>

		<% else %>
			<h1>Hello</h1>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %>
			<%= link_to "Login", new_user_session_path, class: "btn btn-success"%>
		<% end %>
	</p>
	
</div>

app/views/pages/about.html.erb
	<h1>PhotoRack</h1>
	<p>
	Welcome to my simple photorack. </br> 
	Sit back, grab a cup of coffee (or tea) and enjoy!
	</p>

app/views/pins/_form.html.erb
<%= form_for pin, html: { multipart: true } do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" class = "form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field" class = "form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <br>
  <div class="actions" class = "form-group">
    <%= f.submit class: "btn btn-primary btn-lg"%>
  </div>

<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>


<div id="pins" class="transitions-enabled">

	<!-- generate box panel for each pin --> 
	<% @pins.each do |pin| %>
		<div class="box panel panel-default">
	    <%= link_to image_tag(pin.image.url(:medium)), pin_path(pin) %>
	    <div class="panel-body">
		    <%= pin.description %>  
		    <p>by <strong><%= pin.user.username if pin.user %></strong></p>

		    <!-- if user logged in -->
		    <% if pin.user == current_user %>
			    <div class="actions">
				    <%= link_to edit_pin_path(pin) do %>
				    	<span class="glyphicon glyphicon-edit"></span>Edit
				    <% end %>
				    <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
				    	<span class="glyphicon glyphicon-trash"></span>Delete
				    <% end %>
				   </div>
			  <% end %>
				<!-- end user logged in -->

		   </div><!-- panel body --> 
		 </div><!-- box panel default -->
	<% end %>
	<!-- generate box panel for each pin -->

</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<hr>
<%= link_to 'Back', pins_path, class: "btn btn-default" %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path, class: "btn btn-default" %>


<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div><!-- panel heading-->
			<div class="panel-footer center">
				<p><%= @pin.description %></p>
				<p>By <strong><%= @pin.user.username if @pin.user %></strong></p>
				<%= link_to @pin.image.url, class: "btn btn-default" do %>
					High Res
				<% end %>
				<% if @pin.user == current_user %>
					<%= link_to edit_pin_path(@pin), class: "btn btn-default" do %>
						<span class="glyphicon glyphicon-edit"></span>Edit
					<% end %>
				<% end %>
			</div>
	</div><!-- panel default-->
</div><!-- col offset-->
 